# Generated by Django 3.1.1 on 2020-12-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsvp', '0001_squashed_0038_auto_20201203_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_items',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='details',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='documents',
        ),
        migrations.AddField(
            model_name='auctiondetail',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hsvp.auction'),
        ),
        migrations.AddField(
            model_name='document',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='hsvp.auction'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url_1',
            field=models.CharField(default='posts/default.jpg', max_length=100, verbose_name='Document_Image_1'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url_2',
            field=models.CharField(default='posts/default.jpg', max_length=100, verbose_name='Document_Image_2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='auction_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_items', to='hsvp.auctiondetail'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name of item that will be auctioned'),
        ),
    ]
